/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateCardDto
 */
export interface CreateCardDto {

    /**
     * @type {string}
     * @memberof CreateCardDto
     * @example 3abecb07-ce94-4fb6-9988-d2fbcac571ad
     */
    accountID: string;

    /**
     * @type {string}
     * @memberof CreateCardDto
     * @example 411111111111
     */
    cardNumber: string;

    /**
     * @type {Date}
     * @memberof CreateCardDto
     * @example 2024-07-10T06:52:41.152Z
     */
    expirationDate: Date;

    /**
     * @type {number}
     * @memberof CreateCardDto
     * @example 123
     */
    CVV: number;

    /**
     * @type {Date}
     * @memberof CreateCardDto
     * @example 2024-07-10T06:52:41.152Z
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof CreateCardDto
     * @example 2024-07-10T06:52:41.152Z
     */
    updatedAt?: Date;
}
