/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateNotificationDto
 */
export interface CreateNotificationDto {

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     * @example 98ef3ec0-9f87-442e-8859-50150b8b485c
     */
    userID: string;

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     * @example Dear John, your salary of 50,000$ has been credited to your account on 01/03/2023.
     */
    message: string;

    /**
     * @type {boolean}
     * @memberof CreateNotificationDto
     * @example false
     */
    isRead?: boolean;

    /**
     * @type {Date}
     * @memberof CreateNotificationDto
     * @example 2024-07-10T06:52:41.155Z
     */
    createdAt?: Date;
}
