/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {

    /**
     * @type {string}
     * @memberof CreateUserDto
     * @example John
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     * @example Doe
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     * @example john.doe@gmail.com
     */
    email: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     * @example xxxxxxxx
     */
    password: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     * @example JohnDoe
     */
    userName: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     * @example 1234123423
     */
    phoneNumber: string;

    /**
     * @type {Date}
     * @memberof CreateUserDto
     * @example 2024-07-10T06:52:41.151Z
     */
    dateOfBirth: Date;

    /**
     * @type {Date}
     * @memberof CreateUserDto
     * @example 2024-07-10T06:52:41.151Z
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof CreateUserDto
     * @example 2024-07-10T06:52:41.151Z
     */
    updatedAt?: Date;
}
