/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAccountPreferencesDto
 */
export interface CreateAccountPreferencesDto {

    /**
     * @type {string}
     * @memberof CreateAccountPreferencesDto
     * @example c7ac2c51-7768-442d-83fe-c9bac1257013
     */
    userID: string;

    /**
     * @type {boolean}
     * @memberof CreateAccountPreferencesDto
     * @example true
     */
    emailNotifications?: boolean;

    /**
     * @type {boolean}
     * @memberof CreateAccountPreferencesDto
     * @example true
     */
    sMSNotifications?: boolean;

    /**
     * @type {boolean}
     * @memberof CreateAccountPreferencesDto
     * @example true
     */
    pushNotifications?: boolean;

    /**
     * @type {boolean}
     * @memberof CreateAccountPreferencesDto
     * @example true
     */
    enableTwoFactorAuth?: boolean;

    /**
     * @type {Date}
     * @memberof CreateAccountPreferencesDto
     * @example 2024-07-10T06:52:41.025Z
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof CreateAccountPreferencesDto
     * @example 2024-07-10T06:52:41.025Z
     */
    updatedAt?: Date;
}
