/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateCardDto
 */
export interface UpdateCardDto {

    /**
     * @type {string}
     * @memberof UpdateCardDto
     * @example 6a4d6c53-4fe7-4648-9d5e-49faefc85b44
     */
    cardID: string;

    /**
     * @type {string}
     * @memberof UpdateCardDto
     * @example 1e364f38-1d7c-4881-b842-663a7855ba45
     */
    accountID: string;

    /**
     * @type {string}
     * @memberof UpdateCardDto
     * @example 4111111111111111
     */
    cardNumber: string;

    /**
     * @type {Date}
     * @memberof UpdateCardDto
     * @example 2024-07-10T06:52:41.153Z
     */
    expirationDate: Date;

    /**
     * @type {number}
     * @memberof UpdateCardDto
     * @example 123
     */
    CVV: number;

    /**
     * @type {Date}
     * @memberof UpdateCardDto
     * @example 2024-07-10T06:52:41.153Z
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof UpdateCardDto
     * @example 2024-07-10T06:52:41.153Z
     */
    updatedAt?: Date;
}
