/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransactionStatus } from './transaction-status';
 /**
 * 
 *
 * @export
 * @interface UpdateLoanTransactionDto
 */
export interface UpdateLoanTransactionDto {

    /**
     * @type {string}
     * @memberof UpdateLoanTransactionDto
     * @example 3a711828-45c1-4f1c-843a-96a4d4d82a66
     */
    transactionID: string;

    /**
     * @type {string}
     * @memberof UpdateLoanTransactionDto
     * @example 099aee00-e693-4278-8448-b7e9cbc83a57
     */
    fromAccountID?: string;

    /**
     * @type {string}
     * @memberof UpdateLoanTransactionDto
     * @example 7fe72f96-9184-4641-b8f6-37231862028a
     */
    toAccountID?: string;

    /**
     * @type {number}
     * @memberof UpdateLoanTransactionDto
     * @example 10.9
     */
    amount?: number;

    /**
     * @type {Date}
     * @memberof UpdateLoanTransactionDto
     * @example 2024-07-10T06:52:41.158Z
     */
    transactionDate?: Date;

    /**
     * @type {TransactionStatus}
     * @memberof UpdateLoanTransactionDto
     */
    transactionStatus?: TransactionStatus;
}
