/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LoanAccountStatus } from './loan-account-status';
import { LoanType } from './loan-type';
/**
 *
 *
 * @export
 * @interface UpdateLoanDto
 */
export interface UpdateLoanDto {
  /**
   * @type {string}
   * @memberof UpdateLoanDto
   * @example b07c6a3d-a366-487b-b1c6-0c83a842f73a
   */
  LoanID: string;

  /**
   * @type {string}
   * @memberof UpdateLoanDto
   * @example 82cba0c1-00d7-46ca-904a-6558fe953cee
   */
  UserID: string;

  /**
   * @type {string}
   * @memberof UpdateLoanDto
   * @example a7c94318-3caf-4dcd-985e-a9f0320abc77
   */
  BankID: string;

  /**
   * @type {string}
   * @memberof UpdateLoanDto
   * @example 1234123412341234
   */
  AccountNumber: string;

  /**
   * @type {LoanType}
   * @memberof UpdateLoanDto
   */
  LoanType: LoanType;

  /**
   * @type {number}
   * @memberof UpdateLoanDto
   * @example 3972000
   */
  LoanAmount: number;

  /**
   * @type {number}
   * @memberof UpdateLoanDto
   * @example 9.3
   */
  InterestRate: number;

  /**
   * @type {number}
   * @memberof UpdateLoanDto
   * @example 360
   */
  LoanTerm: number;

  /**
   * @type {string}
   * @memberof UpdateLoanDto
   * @example 2024-07-10T06:52:41.154Z
   */
  LoanStartDate: string;

  /**
   * @type {string}
   * @memberof UpdateLoanDto
   * @example 2024-07-10T06:52:41.154Z
   */
  LoanEndDate: string;

  /**
   * @type {number}
   * @memberof UpdateLoanDto
   * @example 360
   */
  RemainingTenure: number;

  /**
   * @type {LoanAccountStatus}
   * @memberof UpdateLoanDto
   */
  LoanStatus: LoanAccountStatus;

  /**
   * @type {Date}
   * @memberof UpdateLoanDto
   * @example 2024-07-10T06:52:41.154Z
   */
  CreatedAt: Date;

  /**
   * @type {Date}
   * @memberof UpdateLoanDto
   * @example 2024-07-10T06:52:41.154Z
   */
  UpdatedAt: Date;
}
