/* tslint:disable */
/* eslint-disable */
/**
 * MyBank API
 * This Swagger document provides a comprehensive overview of the online banking application's API, including the available endpoints, authentication mechanisms, data models, and error handling. Developers can use this documentation to integrate the banking application with their own systems and client applications, ensuring a seamless and secure user experience.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateNotificationDto
 */
export interface UpdateNotificationDto {

    /**
     * @type {string}
     * @memberof UpdateNotificationDto
     * @example 6955b3b0-a3ea-4743-810a-adcaa9d8e527
     */
    NotificationID: string;

    /**
     * @type {string}
     * @memberof UpdateNotificationDto
     * @example 98ef3ec0-9f87-442e-8859-50150b8b485c
     */
    UserID: string;

    /**
     * @type {string}
     * @memberof UpdateNotificationDto
     * @example Dear John, your salary of 50,000$ has been credited to your account on 01/03/2023.
     */
    Message?: string;

    /**
     * @type {boolean}
     * @memberof UpdateNotificationDto
     * @example false
     */
    IsRead?: boolean;

    /**
     * @type {Date}
     * @memberof UpdateNotificationDto
     * @example 2024-07-10T06:52:41.155Z
     */
    CreatedAt?: Date;
}
